changelog:
  - title: "&cNeue Kisten"
    date: "&703.03.2025"
    content:
      - "&7Ein neuer Monat bringt neue &eKisten&7!"
      - "&fFreut euch auf die &cSchmelzpicke V4&f, die wirklich alles schmelzen kann, und &9Titanschlag&f, den neuen Streitkolben aus der &e1.21.3&f."
      - "&fAußerdem neu: &dRiesen-& und &5Zwergpilze&f, mit denen ihr eure Größe verändern könnt!"
      - "&fDas und vieles mehr gibt es jetzt in den neuen Kisten. Sichert sie euch und genießt die ersten warmen Tage mit &4OPSUCHT&f!"

  - title: "&6Frühlings-Update"
    date: "&715.04.2025"
    content:
      - "&fDas Frühlings-Update bringt viele neue Features!"
      - "&aNeue Events, um exklusive Belohnungen zu verdienen."
      - "&bPerformance-Verbesserungen und Fehlerbehebungen."
      - "&dNeue kosmetische Gegenstände und Skins!"

  - title: "&3Community-Verbesserungen"
    date: "&701.05.2025"
    content:
      - "&fBasierend auf eurem Feedback haben wir folgende Änderungen vorgenommen:"
      - "&2✔ Verbesserte Server-Stabilität für ein flüssigeres Spielerlebnis."
      - "&e✔ Mehr Belohnungen für aktive Spieler!"
      - "&6✔ Neue Minispiele und Herausforderungen!"
