changelog:
  - title: "Neue Kisten"
    date: "03.03.2025"
    content:
      - "Ein neuer Monat bringt neue **Kisten**!"
      - "Freut euch auf die **Schmelzpicke V4**, die wirklich alles schmelzen kann, und **Titanschlag**, den neuen Streitkolben aus der **1.21.3**."
      - "Außerdem neu: **Riesen- und Zwergpilze**, mit denen ihr eure Größe verändern könnt!"
      - "Das und vieles mehr gibt es jetzt in den neuen Kisten. Sichert sie euch und genießt die ersten warmen Tage mit **OPSUCHT**!"

  - title: "Frühlings-Update"
    date: "15.04.2025"
    content:
      - "Das Frühlings-Update bringt viele neue Features!"
      - "Neue Events, um exklusive Belohnungen zu verdienen."
      - "Performance-Verbesserungen und Fehlerbehebungen."
      - "Neue kosmetische Gegenstände und Skins!"

  - title: "Community-Verbesserungen"
    date: "01.05.2025"
    content:
      - "Basierend auf eurem Feedback haben wir folgende Änderungen vorgenommen:"
      - "Verbesserte Server-Stabilität für ein flüssigeres Spielerlebnis."
      - "Mehr Belohnungen für aktive Spieler!"
      - "Neue Minispiele und Herausforderungen!"
